#Pre-procesado del dataset

# **Inspeccionar el dataset**

In [9]:
#Improtamos las librerias que necesitamos
import pandas as pd
import numpy as np

In [10]:
#Subimos el dataset
df = pd.read_csv('adult.csv',header=0)

In [11]:
#Observamos de manera visual como son nuestros datos y como est√°n estructurados
df.head(10)

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,gains
0,50.0,Self-emp-not-inc,83311,Bachelors,13.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13.0,United-States,<=50K
1,38.0,Private,215646,HS-grad,9.0,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40.0,United-States,<=50K
2,53.0,Private,234721,11th,7.0,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40.0,United-States,<=50K
3,28.0,Private,338409,Bachelors,13.0,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40.0,Cuba,<=50K
4,37.0,Private,284582,Masters,14.0,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40.0,United-States,<=50K
5,49.0,Private,160187,9th,5.0,Married-spouse-absent,Other-service,Not-in-family,Black,Female,0,0,16.0,Jamaica,<=50K
6,52.0,Self-emp-not-inc,209642,HS-grad,9.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45.0,United-States,>50K
7,31.0,Private,45781,Masters,14.0,Never-married,Prof-specialty,Not-in-family,White,Female,14084,0,50.0,United-States,>50K
8,42.0,Private,159449,Bachelors,13.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,5178,0,40.0,United-States,>50K
9,37.0,Private,280464,Some-college,10.0,Married-civ-spouse,Exec-managerial,Husband,Black,Male,0,0,80.0,United-States,>50K

In [12]:
#Obtenemos informaci√≥n m√°s detallada
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32560 entries, 0 to 32559
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32559 non-null  float64
 1   workclass       32560 non-null  object
 2   fnlwgt          32560 non-null  int64
 3   education       32560 non-null  object
 4   education-num   32554 non-null  float64
 5   marital-status  32560 non-null  object
 6   occupation      32560 non-null  object
 7   relationship    32560 non-null  object
 8   race            32560 non-null  object
 9   sex             32560 non-null  object
 10  capital-gain    32560 non-null  int64
 11  capital-loss    32560 non-null  int64
 12  hours-per-week  32552 non-null  float64
 13  native-country  32560 non-null  object
 14  gains           32560 non-null  object
dtypes: float64(3), int64(3), object(9)
memory usage: 3.7+ MB

# **Pre-procesado**

### **Datos categoricos**

#### **Workclass**

In [13]:
def encode_label(df):
    return df.astype('category').cat.codes

Vamos a analizar cuantos valores distintos tenemos de cada una de las clases categoricas para estudiar si las transformamos directamente a numeros o las podemos agrupar primero.

In [14]:
df['workclass'].unique()

array([' Self-emp-not-inc', ' Private', ' State-gov', ' Federal-gov',
       ' Local-gov', ' ?', ' Self-emp-inc', ' ', ' Without-pay',
       ' Never-worked'], dtype=object)

Ante la situaci√≥n anterior nos salta una alarma, es decir, un valor nulo puede ser expresado como Nan, por lo tanto lo podemos identificar con funciones de pandas, pero adem√°s en este caso tenemos sitaciones en las que nos aparece un '?', que no nos da ninguna informaci√≥n. Debemos mirar por lo tanto cuantas veces nos encontramos con esta situaci√≥n en esta columna y en el resto.

In [15]:
df['workclass'].value_counts()

 Private             22693
 Self-emp-not-inc     2541
 Local-gov            2093
 ?                    1836
 State-gov            1297
 Self-emp-inc         1116
 Federal-gov           960
 Without-pay            14
 Never-worked            7
                         3
Name: workclass, dtype: int64

¬øC√≥mo solventamos el problema? Tenemos varias opciones:

a)  en primer lugar eliminar todas las filas, podr√≠a ser una posibilidad debido a que solo afecta a un 5% de los datos.

b) Otro caso podr√≠a ser inferir su valor.

c)Y otra situaci√≥n podr√≠a ser eliminar la columna directamente.

La segunda situaci√≥n es m√°s com√∫n en el caso de los valores num√©ricos ya que se puede derivar una media, que a√∫n no representando el valor original se aproxima, sin embargo en el caso categ√≥rico el hecho de poner un valor implica que estamos poniendo un valor determinista. Por esta raz√≥n la primera opci√≥n dado que solo estamos ante un 5% de los datos + las 3 filas que no tienen valor ser√°n eliminadas.

In [16]:
df.drop(df[df['workclass'] == ' '].index, inplace = True)
df.drop(df[df['workclass'] == ' ?'].index, inplace = True)

In [17]:
df['workclass'].value_counts()

 Private             22693
 Self-emp-not-inc     2541
 Local-gov            2093
 State-gov            1297
 Self-emp-inc         1116
 Federal-gov           960
 Without-pay            14
 Never-worked            7
Name: workclass, dtype: int64

In [18]:
df['workclass'] = encode_label(df['workclass'])

In [19]:
df['workclass'].value_counts()

3    22693
5     2541
1     2093
6     1297
4     1116
0      960
7       14
2        7
Name: workclass, dtype: int64

#### **Education, education-num**

Nos quedamos con education-num

In [20]:
df.drop(['education'], axis=1, inplace = True)

In [21]:
df.isnull().sum()

age               1
workclass         0
fnlwgt            0
education-num     6
marital-status    0
occupation        0
relationship      0
race              0
sex               0
capital-gain      0
capital-loss      0
hours-per-week    8
native-country    0
gains             0
dtype: int64

In [22]:
# Como no hay muchos nulos, eliminamos las filas

df = df.dropna()

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 30706 entries, 0 to 32559
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             30706 non-null  float64
 1   workclass       30706 non-null  int8
 2   fnlwgt          30706 non-null  int64
 3   education-num   30706 non-null  float64
 4   marital-status  30706 non-null  object
 5   occupation      30706 non-null  object
 6   relationship    30706 non-null  object
 7   race            30706 non-null  object
 8   sex             30706 non-null  object
 9   capital-gain    30706 non-null  int64
 10  capital-loss    30706 non-null  int64
 11  hours-per-week  30706 non-null  float64
 12  native-country  30706 non-null  object
 13  gains           30706 non-null  object
dtypes: float64(3), int64(3), int8(1), object(7)
memory usage: 3.3+ MB

#### **Marital status**

In [24]:
df['marital-status'].value_counts()

 Married-civ-spouse       14332
 Never-married             9909
 Divorced                  4256
 Separated                  959
 Widowed                    840
 Married-spouse-absent      389
 Married-AF-spouse           21
Name: marital-status, dtype: int64

In [25]:
df['marital-status'] = encode_label(df['marital-status'])

#### **Occupation**

In [26]:
df['occupation'].value_counts()

 Prof-specialty       4138
 Craft-repair         4097
 Exec-managerial      4065
 Adm-clerical         3769
 Sales                3648
 Other-service        3289
 Machine-op-inspct    2002
 Transport-moving     1594
 Handlers-cleaners    1370
 Farming-fishing       993
 Tech-support          927
 Protective-serv       649
 Priv-house-serv       149
 Armed-Forces            9
 ?                       7
Name: occupation, dtype: int64

In [27]:
df.drop(df[df['occupation'] == ' ?'].index, inplace = True)

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 30699 entries, 0 to 32559
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             30699 non-null  float64
 1   workclass       30699 non-null  int8
 2   fnlwgt          30699 non-null  int64
 3   education-num   30699 non-null  float64
 4   marital-status  30699 non-null  int8
 5   occupation      30699 non-null  object
 6   relationship    30699 non-null  object
 7   race            30699 non-null  object
 8   sex             30699 non-null  object
 9   capital-gain    30699 non-null  int64
 10  capital-loss    30699 non-null  int64
 11  hours-per-week  30699 non-null  float64
 12  native-country  30699 non-null  object
 13  gains           30699 non-null  object
dtypes: float64(3), int64(3), int8(2), object(6)
memory usage: 3.1+ MB

In [29]:
df['occupation'] = encode_label(df['occupation'])

#### **Relationship**

In [30]:
df['relationship'].value_counts()

 Husband           12698
 Not-in-family      7858
 Own-child          4522
 Unmarried          3270
 Wife               1433
 Other-relative      918
Name: relationship, dtype: int64

In [31]:
df['relationship'] = encode_label(df['relationship'])

#### **Sexo**

In [32]:
df['Sex'] = df['sex'].map({'Male': 1, 'Female':0})

In [33]:
df.head()

,age,workclass,fnlwgt,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,gains,Sex
0,50.0,5,83311,13.0,2,3,0,White,Male,0,0,13.0,United-States,<=50K,NaN
1,38.0,3,215646,9.0,0,5,1,White,Male,0,0,40.0,United-States,<=50K,NaN
2,53.0,3,234721,7.0,2,5,0,Black,Male,0,0,40.0,United-States,<=50K,NaN
3,28.0,3,338409,13.0,2,9,5,Black,Female,0,0,40.0,Cuba,<=50K,NaN
4,37.0,3,284582,14.0,2,3,5,White,Female,0,0,40.0,United-States,<=50K,NaN

¬øQu√© est√° sucediendo?

In [34]:
#Una de las problem√°ticas que nos podemos encontrar es que aunque a simple vista nos parezca que est√° escrito de una manera en el dataset lo est√° de otra.
df['sex'].unique()

array([' Male', ' Female'], dtype=object)

In [35]:
df['sex'] = df['sex'].map({' Male': 1, ' Female':0})

In [36]:
df.drop('Sex',axis='columns',inplace = True)

In [37]:
df.head()

,age,workclass,fnlwgt,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,gains
0,50.0,5,83311,13.0,2,3,0,White,1,0,0,13.0,United-States,<=50K
1,38.0,3,215646,9.0,0,5,1,White,1,0,0,40.0,United-States,<=50K
2,53.0,3,234721,7.0,2,5,0,Black,1,0,0,40.0,United-States,<=50K
3,28.0,3,338409,13.0,2,9,5,Black,0,0,0,40.0,Cuba,<=50K
4,37.0,3,284582,14.0,2,3,5,White,0,0,0,40.0,United-States,<=50K

#### **Race**

In [ ]:
df['race'].value_counts()
#Nuestros datos tienen un bias importante o no?.

 White                 26302
 Black                  2909
 Asian-Pac-Islander      974
 Amer-Indian-Eskimo      286
 Other                   248
                           2
Name: race, dtype: int64

In [ ]:
df['race'].unique()

array([' White', ' Black', ' Asian-Pac-Islander', ' Amer-Indian-Eskimo',
       ' Other', ' '], dtype=object)

In [ ]:
#Estudio de un posible BIAS -> porcentaje de datos de cada una de las clases.
black_high_income = df[(df['race']==' Black') & (df['gains']==' >50K')].shape[0]
black_low_income = df[(df['race']==' Black') & (df['gains']==' <=50K')].shape[0]
total = df[(df['race']==' Black')].shape[0]
#print('black_high_income',black_high_income,'black_low_income',black_low_income,'total black',total)
print('total',total,'black_high_income',(black_high_income/total)*100,'black_low_income',(black_low_income/total)*100)
print('')
white_high_income = df[(df['race']==' White') & (df['gains']==' >50K')].shape[0]
white_low_income = df[(df['race']==' White') & (df['gains']==' <=50K')].shape[0]
total = df[(df['race']==' White')].shape[0]

#print('white_high_income',white_high_income,'white_low_income',white_low_income)
print('total',total,'white_high_income',(white_high_income/total)*100,'white_low_income',(white_low_income/total)*100)
print('')

Asian_Pac_Islander_high_income = df[(df['race']==' Asian-Pac-Islander') & (df['gains']==' >50K')].shape[0]
Asian_Pac_Islander_low_income = df[(df['race']==' Asian-Pac-Islander') & (df['gains']==' <=50K')].shape[0]
total = df[(df['race']==' Asian-Pac-Islander')].shape[0]

#print('Asian_Pac_Islander_high_income',Asian_Pac_Islander_high_income,'Asian_Pac_Islander_low_income',Asian_Pac_Islander_low_income)
print('total',total,'Asian_Pac_Islander_high_income',(Asian_Pac_Islander_high_income/total)*100,'Asian_Pac_Islander_low_income',(Asian_Pac_Islander_low_income/total)*100)
print('')

Amer_Indian_Eskimo_high_income = df[(df['race']==' Amer-Indian-Eskimo') & (df['gains']==' >50K')].shape[0]
Amer_Indian_Eskimo_low_income = df[(df['race']==' Amer-Indian-Eskimo') & (df['gains']==' <=50K')].shape[0]
total = df[(df['race']==' Amer-Indian-Eskimo')].shape[0]
#print('Amer-Indian-Eskimo_high_income',Amer_Indian_Eskimo_high_income,'Amer-Indian-Eskimo_low_income',Amer_Indian_Eskimo_low_income)
print('total',total,'Amer-Indian-Eskimo_high_income',(Amer_Indian_Eskimo_high_income/total)*100,'Amer-Indian-Eskimo_low_income',(Amer_Indian_Eskimo_low_income/total)*100)
print('')

total 2909 black_high_income 12.994156067377105 black_low_income 87.0058439326229

total 26302 white_high_income 26.397232149646417 white_low_income 73.60276785035359

total 974 Asian_Pac_Islander_high_income 27.823408624229977 Asian_Pac_Islander_low_income 72.17659137577002

total 286 Amer-Indian-Eskimo_high_income 11.888111888111888 Amer-Indian-Eskimo_low_income 88.11188811188812

In [ ]:
df.drop(df[df['race'] == ' '].index, inplace = True)

In [ ]:
df['race'] = encode_label(df['race'])

<ipython-input-42-f6ac99ec2fc0>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['race'] = encode_label(df['race'])

In [ ]:
df['race'].value_counts()
#transformamos directamente en valores numericos en los que cada n√∫mero representar√° una clase

5    26286
3     2905
2      972
1      286
4      248
0        2
Name: race, dtype: int64

#### **Native country**

In [ ]:
df['native-country'].value_counts()

 United-States                 27487
 Mexico                          610
 ?                               555
 Philippines                     188
 Germany                         128
 Puerto-Rico                     109
 Canada                          107
 India                           100
 El-Salvador                     100
 Cuba                             92
 England                          86
 Jamaica                          79
 South                            71
 China                            68
 Italy                            68
 Dominican-Republic               67
 Vietnam                          64
 Guatemala                        63
 Japan                            59
 Poland                           56
 Columbia                         56
 Iran                             42
 Taiwan                           42
 Haiti                            42
 Portugal                         34
 Nicaragua                        33
 Peru                             30
 Greece                           29
 France                           27
 Ecuador                          27
 Ireland                          24
 Hong                             19
 Cambodia                         18
 Trinadad&Tobago                  18
 Thailand                         17
 Laos                             17
 Yugoslavia                       16
 Outlying-US(Guam-USVI-etc)       14
 Hungary                          13
 Honduras                         12
 Scotland                         11
 Holand-Netherlands                1
Name: native-country, dtype: int64

### **Datos num√©ricos**

#### **Horas por semana**

In [ ]:
df['hours-per-week'].value_counts()

40.0    14521
50.0     2762
45.0     1791
60.0     1439
35.0     1204
        ...
92.0        1
94.0        1
82.0        1
87.0        1
74.0        1
Name: hours-per-week, Length: 94, dtype: int64

In [ ]:
(df['hours-per-week']<40).value_counts()

False    23899
True      6820
Name: hours-per-week, dtype: int64

Por lo tanto podemos dividirlo en lo que nostros consideramos como "media jornada", "jornada completa","inferior a media jornada","superior a jornada completa"

In [38]:
df['Hour-bin'] = df['hours-per-week']
df.loc[df['Hour-bin'] == 0, 'Hour-bin'] = 0
df.loc[df['Hour-bin'] < 20, 'Hour-bin'] = 1
df.loc[(df['Hour-bin'] >= 20) & (df['Hour-bin'] < 40), 'Hour-bin'] = 2
df.loc[(df['Hour-bin'] == 40), 'Hour-bin'] = 3
df.loc[(df['Hour-bin'] > 40), 'Hour-bin'] = 4

In [39]:
#Hacemos dummies
df['No trabaja'] = df['Hour-bin'].map(lambda s: 1 if s == 0 else 0)
df['Menos de media jornada'] = df['Hour-bin'].map(lambda s: 1 if s == 1 else 0)
df['Media jornada'] = df['Hour-bin'].map(lambda s: 1 if s == 2 else 0)
df['Jornada completa'] = df['Hour-bin'].map(lambda s: 1 if s == 3 else 0)
df['Superior a jornada completa'] = df['Hour-bin'].map(lambda s: 1 if s == 4 else 0)

In [41]:
df.describe()

,age,workclass,fnlwgt,education-num,marital-status,occupation,relationship,sex,capital-gain,capital-loss,hours-per-week,Hour-bin,No trabaja,Menos de media jornada,Media jornada,Jornada completa,Superior a jornada completa
count,30699.000000,30699.000000,3.069900e+04,30699.000000,30699.000000,30699.00000,30699.000000,30699.000000,30699.000000,30699.000000,30699.000000,30699.000000,30699.0,30699.000000,30699.000000,30699.000000,30699.000000
mean,38.444803,3.100101,1.898527e+05,10.130493,2.583179,5.96609,1.417147,0.676765,1106.472914,88.965243,40.951236,3.039154,0.0,0.044138,0.177791,0.472849,0.305222
std,13.117481,1.139461,1.054609e+05,2.562638,1.495714,4.02587,1.601355,0.467719,7500.124874,405.776688,11.984457,0.811205,0.0,0.205406,0.382343,0.499270,0.460509
min,17.000000,0.000000,1.376900e+04,1.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.0,0.000000,0.000000,0.000000,0.000000
25%,28.000000,3.000000,1.178330e+05,9.000000,2.000000,2.00000,0.000000,0.000000,0.000000,0.000000,40.000000,3.000000,0.0,0.000000,0.000000,0.000000,0.000000
50%,37.000000,3.000000,1.785170e+05,10.000000,2.000000,6.00000,1.000000,1.000000,0.000000,0.000000,40.000000,3.000000,0.0,0.000000,0.000000,0.000000,0.000000
75%,47.000000,3.000000,2.372995e+05,13.000000,4.000000,9.00000,3.000000,1.000000,0.000000,0.000000,45.000000,4.000000,0.0,0.000000,0.000000,1.000000,1.000000
max,90.000000,7.000000,1.484705e+06,16.000000,6.000000,13.00000,5.000000,1.000000,99999.000000,4356.000000,99.000000,4.000000,0.0,1.000000,1.000000,1.000000,1.000000